---
# Elasticsearch Ansible Variables
# Ref: https://github.com/Traackr/ansible-elasticsearch

elasticsearch_version: 1.7.3
elasticsearch_apt_java_package: oracle-java8-installer
elasticsearch_java_home: /usr/lib/jvm/java-8-oracle
elasticsearch_heap_size: 1g
elasticsearch_max_open_files: 65535
elasticsearch_timezone: "America/New_York"
elasticsearch_node_max_local_storage_nodes: 1
elasticsearch_index_mapper_dynamic: "true"
elasticsearch_memory_bootstrap_mlockall: "true"
elasticsearch_install_java: "true"
elasticsearch_service_startonboot: yes
